#!/usr/bin/env python3
"""Write game/data/maps/gale-1.txt, the Windswept Meadow for the Godot client.

It has the same layout as the demo map (meadow, terrace, stairs, lookout, spur,
pond and the arrival clearing), redrawn for the Whispers of Avalon tiles:
- south-facing cliff faces are two cells tall, as the art paints them;
- west- and east-facing faces are one cell wide.

Elevation codes:
- a digit is a level;
- 'C' is a cliff face (blocked);
- 'S' is a stair cell, which joins its neighbours' levels.

Ground codes:
- '.' grass, ':' sand path, '~' water, 'f' flowers (decoration);
- obstacles: T/t/O/D trees, u stump, B/b bushes, r rock, '#' forest edge,
  '=' low hedge edge.

The script checks that walkable cells on different levels meet only at stairs,
because walking never changes level anywhere else.
"""
import os
import sys

W, H = 44, 34
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
OUT = os.path.join(ROOT, "game", "data", "maps", "gale-1.txt")

BLOCKING = set("~TtODuBbr#=")


def build():
    elev = [["0"] * W for _ in range(H)]
    ground = [["."] * W for _ in range(H)]

    def area(x0, y0, x1, y1, grid, value):
        for y in range(y0, y1 + 1):
            for x in range(x0, x1 + 1):
                grid[y][x] = value

    # Terrace (level 1) across the north, with a two-cell south face.
    area(0, 0, W - 1, 10, elev, "1")
    area(0, 11, W - 1, 12, elev, "C")
    area(8, 11, 10, 12, elev, "S")              # the stairs, three wide

    # Lookout (level 2) in the north-east: a one-cell west face (jumpable
    # from the terrace) and a two-cell south face (too tall to jump at first).
    area(27, 1, W - 2, 4, elev, "2")
    area(26, 1, 26, 6, elev, "C")
    area(26, 5, 37, 6, elev, "C")
    # Its spur runs south to the terrace edge and overhangs the meadow,
    # two levels up. It has a one-cell west face.
    area(38, 5, W - 2, 10, elev, "2")
    area(37, 5, 37, 10, elev, "C")

    # Pond in the south-east meadow (the art's pond border is rectangular
    # with rounded corners).
    area(31, 23, 38, 27, ground, "~")

    # Sand path from the foot of the stairs to the arrival clearing.
    area(8, 13, 10, 25, ground, ":")
    area(8, 25, 20, 27, ground, ":")
    area(11, 28, 15, 30, ground, ":")

    # The forest edge around the map ('=' along the south: low bushes only,
    # so nothing tall hides the meadow's southern edge).
    for x in range(W):
        ground[0][x] = "#"
        ground[H - 1][x] = "="
    for y in range(H):
        ground[y][0] = ground[y][W - 1] = "#"
    # Map edges are never cliff faces: nothing should cross them.
    for y in range(H):
        for x in (0, W - 1):
            if elev[y][x] in "CS":
                elev[y][x] = "1" if y <= 12 else "0"

    # Trees (trunk cell blocked) and other obstacles.
    for x, y, c in [
        (3, 3, "T"), (6, 7, "t"), (19, 2, "O"), (23, 8, "T"), (31, 8, "t"),
        (3, 16, "O"), (5, 22, "T"), (2, 29, "t"), (24, 31, "b"), (41, 15, "t"),
        (40, 30, "O"), (27, 16, "D"), (18, 15, "u"), (22, 19, "B"),
        (4, 27, "B"), (30, 30, "b"), (16, 5, "b"), (34, 9, "B"),
        (40, 3, "T"), (13, 18, "r"), (25, 26, "r"), (36, 19, "r"),
    ]:
        ground[y][x] = c
    for x, y in [(6, 14), (15, 16), (19, 23), (29, 21), (38, 29), (12, 3),
                 (28, 2), (33, 3), (21, 6), (5, 9)]:
        if ground[y][x] == ".":
            ground[y][x] = "f"
    return elev, ground


def check(elev, ground):
    errors = []

    def walkable(x, y):
        return elev[y][x] != "C" and ground[y][x] not in BLOCKING

    for y in range(H):
        for x in range(W):
            if not walkable(x, y) or elev[y][x] == "S":
                continue
            for dx, dy in ((1, 0), (0, 1), (1, 1), (1, -1)):
                nx, ny = x + dx, y + dy
                if not (0 <= nx < W and 0 <= ny < H) or not walkable(nx, ny):
                    continue
                if elev[ny][nx] == "S":
                    continue
                if elev[ny][nx] != elev[y][x]:
                    errors.append("levels meet at (%d,%d)-(%d,%d)" % (x, y, nx, ny))
    return errors


THINGS = """\
npc|ama|Windkeeper Ama|14|27|ama
npc|wren|Wren the Ridge-runner|12|8|wren
spawn|1101|22|21|16|5|22|20000
spawn|1102|14|6|9|3|7|30000
spawn|1103|33|25|7|6|6|30000
spawn|1104|34|2|6|1|4|40000
spawn|1010|36|17|5|3|3|30000
spawn|1010|20|9|3|1|2|30000
"""


def main():
    elev, ground = build()
    errors = check(elev, ground)
    if errors:
        print("\n".join(errors))
        return 1
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write("// Generated by tools/content/make_meadow.py - edit that, not this.\n")
        f.write("name: gale-1\ntitle: Windswept Meadow\nsize: %d %d\nspawn: 12 29\n" % (W, H))
        f.write("[elevation]\n")
        f.writelines("".join(r) + "\n" for r in elev)
        f.write("[ground]\n")
        f.writelines("".join(r) + "\n" for r in ground)
        f.write("[things]\n" + THINGS)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
