login_port: 6901
new_account: true
main_server: Aethyra
userid: aethyra-char
passwd: change-me-char
account_filename: save/account.txt
gm_account_filename: save/gm_account.txt
login_log_filename: log/login.log
conn_limit_enable: false
