char_ip: 127.0.0.1
char_port: 6121
map_ip: 127.0.0.1
map_port: 5121
userid: aethyra-char
passwd: change-me-char
mapreg_txt: save/mapreg.txt
gm_log: log/gm.log
log_file: log/map.log
map: gale-1.gat
npc: npc/gale-1.txt
